/**
 *  Copyright 2010 Główczyński Tomasz
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License. 
 */

package util;

import model.database.MNISTImagesFile;
import model.database.MNISTLabelsFile;
import java.io.*;

public class MNISTtoPPM extends Object {
  public static void main(String [] args ) {
    MNISTImagesFile imgF = null;
    MNISTLabelsFile lblF = null;
    //MNISTDatabase data = MNISTDatabase.getInstance();
  //  if (args.length!=2) {
    //  System.err.println("MNISTtoPPM syntax: MNISTtoPPM  <img offset>");
   //   System.exit(0);
 //   } else {
      try {

	imgF = new MNISTImagesFile("digitDatabase/t10k-images-idx3-ubyte","r");
	lblF = new MNISTLabelsFile("digitDatabase/t10k-labels-idx1-ubyte","r");
      } catch (FileNotFoundException e) { 
	System.err.println("File not found: " + e);
	System.exit(0);
      } catch (IOException e) {
	System.err.println("IO Exception: " + e);
	System.exit(0);
      }
      imgF.setCurr(Integer.parseInt(args[0]));
      lblF.setCurr(Integer.parseInt(args[0]));
     // if (  args[1].equals("image"))
        printPPMToStdOut(imgF, lblF);
    //  else
     //   printLabelToStdErr(lblF);
    }
 // }

  public static void printLabelToStdErr(MNISTLabelsFile lblF) {
    //Prints to stderr the number that the image is supposed to be 
    System.out.println(lblF.readData());
  } 

  public static void printPPMToStdOut(MNISTImagesFile imgF, MNISTLabelsFile lblF) {
    //Prints to stdout the ppm file of selected image (per ppm format in man ppm) 
    String s = null;
    int [][] dat = imgF.readData();
    System.out.println("P3");
    System.out.println(""+ imgF.getRows() + " " + imgF.getCols() + " 255");
    System.out.println("# autogenerated by MNISTtoPPM");
    System.out.println("# this was drawn as a " + lblF.readData());
    System.out.println("# " + imgF.name());
    System.out.println("# " + imgF.status());
    for (int i=0;i<imgF.getRows();i++) {
      s="";
      for(int j=0;j<imgF.getCols();j++)
	s = s + dat[i][j] + " " + dat[i][j] + " " + dat[i][j] + "  ";
      System.out.println(s);
    }
  }
}





